name: coco-ci

on:
  push:
    branches: [ main, wip-tests ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
		- run: npm run build-client
		- run: npm run test-client
		- run: npm run build-server
		- run: npm run test-server
