name: coco-ci

on:
  push:
    branches: [ main, wip-tests ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '15.14'
    - name: Install dependencies
      run: yarn
      run: yarn test-client
